# The following iterative sequence is defined for the set of positive integers:

# n → n/2 (n is even)
# n → 3n + 1 (n is odd)

# Using the rule above and starting with 13, we generate the following sequence:

# 13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

# It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms.
# Although it has not been proved yet (Collatz Problem), it is thought that all starting
# numbers finish at 1.

# Which starting number, under one million, produces the longest chain?

# NOTE: Once the chain starts the terms are allowed to go above one million.

def collatz_sequence_length(integer)
  length = 0
  num = integer
  until num == 1
    num = num % 2 == 0 ? num / 2 : num * 3 + 1
    length += 1
  end
  length + 1
end

def highest_collatz_in_range(max_num_in_range)
  sequence_lengths = {}
  unchecked_numbers = (1..max_num_in_range).to_a.reverse

  unchecked_numbers.each do |num|
    sequence_lengths[num] = collatz_sequence_length(num)
  end

  sequence_lengths.max_by {|number, sequence_length| sequence_length}[0]
end

p highest_collatz_in_range(999_999)

# => 837799

# This takes 5-10 seconds to run. I thought I could refactor it for performance by starting at
# 999,999 and working down, eliminating numbers generated by the sequence. However, this approach
# winds up taking much longer.
