# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
# D = |Pk − Pj| is minimised; what is the value of D?

def nth_pentagonal(n)
  n * (3 * n - 1) / 2
end

def pentagonal?(number)
  # Quadratic formula here. We can reject the other solution, (1 - Math.sqrt...), because it will always
  # be less than 1 and therefore an invalid index.
  pentagonal_index = (1 + Math.sqrt(1 + 24 * number)) / 6.0
  pentagonal_index.to_i == pentagonal_index
end

pentagonals = (1..100).to_a.map {|index| nth_pentagonal(index)}

p pentagonals